from __future__ import annotations
from fastapi import APIRouter
from fastapi.responses import Response
from starlette.middleware.base import BaseHTTPMiddleware

JS=r'''(()=>{
let catalog={tools:[],connectors:[]},filter='all',query='';
const text=value=>escapeHtml(String(value??''));
const label=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const connected=c=>c.state==='healthy';
const enabledTool=item=>['ENABLED','ACTIVE'].includes(String(item.availability||'').toUpperCase());
const availableItem=(item,type)=>type==='integration'?Boolean(item.configured&&item.auth_type==='oauth2_pkce'&&['disconnected','authentication_required','authentication_expired','revoked'].includes(item.state)):['AVAILABLE','CONNECTION_REQUIRED'].includes(String(item.availability||'').toUpperCase());
const statuses={healthy:['Connected','connected'],authentication_expired:['Reconnect required','attention'],authentication_required:['Available','available'],not_configured:['Not configured','attention'],disconnected:['Available','available'],revoked:['Reconnect required','attention'],insufficient_scope:['Permission limited','attention'],permission_denied:['Permission blocked','attention'],disabled:['Disabled','attention'],degraded:['Needs attention','attention'],rate_limited:['Needs attention','attention'],provider_unavailable:['Unavailable','attention'],revocation_pending:['Revocation pending','attention']};
function toolStatus(t){const availability=String(t.availability||'UNAVAILABLE').toUpperCase();if(['PERMISSION_BLOCKED','EMERGENCY_STOP'].includes(availability))return [label(availability),'attention'];if(availability==='CONNECTION_REQUIRED')return ['Connection required','available'];return [label(availability),availability==='AVAILABLE'?'available':'attention']}
function row(item,type){const isApp=type==='integration',state=isApp?(statuses[item.state]||statuses[item.connection_status]||[label(item.state||'Unavailable'),'attention']):toolStatus(item),name=item.name||item.id||item.tool_id||'Unnamed capability',desc=isApp?((item.capabilities||[]).slice(0,3).join(' · ')||`Integration · ${label(item.provider)}`):(item.description||item.capability||'Personal AI capability'),canConnect=isApp&&item.configured&&item.auth_type==='oauth2_pkce'&&!connected(item)&&item.state!=='not_configured',canRevoke=isApp&&['healthy','degraded','rate_limited','authentication_expired','insufficient_scope','revocation_pending'].includes(item.state),badgeClass=connected(item)?'connected':state[1];
return `<article class="section-record apps-record"><span class="section-record-icon ${isApp?'apps-integration':'apps-tool'}">${sectionIcon(isApp?'web':'workflow')}</span><span class="section-record-copy"><span class="section-record-title">${text(name)}</span><span class="section-record-preview">${text(desc)}</span><span class="section-tags"><span class="section-tag">${text(isApp?'Integration':'Tool')}</span>${isApp&&item.read_only?'<span class="section-tag">Read only</span>':''}${!isApp&&item.approval_policy?`<span class="section-tag">${text(label(item.approval_policy))}</span>`:''}</span><span class="section-connection ${badgeClass}"><i aria-hidden="true"></i>${text(state[0])}</span></span><span class="apps-record-actions">${canConnect?`<button type="button" class="apps-connect" aria-label="${item.state==='authentication_expired'||item.state==='revoked'?'Reconnect':'Connect'} ${text(name)}" data-connector-connect="${text(item.id)}">${item.state==='authentication_expired'||item.state==='revoked'?'Reconnect':'Connect'}</button>`:''}${canRevoke?`<button type="button" class="apps-revoke" aria-label="Disconnect ${text(name)}" data-connector-revoke="${text(item.id)}">Disconnect</button>`:''}<button type="button" class="apps-detail-toggle" aria-expanded="false" aria-label="Show details for ${text(name)}">${actionIcon('next')}</button></span><span class="apps-record-detail hidden">${text(isApp?`${(item.capabilities||[]).join(' · ')||'No capabilities listed'}${item.missing_scopes?.length?` · Missing permissions: ${item.missing_scopes.join(', ')}`:''}${item.last_success_at?` · Last healthy ${new Date(item.last_success_at*1000).toLocaleString()}`:''}`:`${item.description||''} · Risk ${item.risk||'not specified'} · ${label(item.approval_policy||'policy controlled')}`)}</span></article>`}
function render(){const body=$('moduleBody'),focus=sectionSearchFocus('appsToolsSearch'),all=[...catalog.tools.map(item=>({item,type:'tool'})),...catalog.connectors.map(item=>({item,type:'integration'}))],matching=all.filter(({item,type})=>{const isConnected=type==='integration'&&connected(item);if(filter==='connected'&&!isConnected)return false;if(filter==='available'&&!availableItem(item,type))return false;if(filter==='tools'&&type!=='tool')return false;if(filter==='integrations'&&type!=='integration')return false;return !query||`${item.name||''} ${item.description||''} ${item.category||''} ${item.provider||''} ${type}`.toLowerCase().includes(query)}),connectedRows=matching.filter(x=>x.type==='integration'&&connected(x.item)),enabledRows=matching.filter(x=>x.type==='tool'&&enabledTool(x.item)),availableRows=matching.filter(x=>availableItem(x.item,x.type)),attentionRows=matching.filter(x=>!connectedRows.includes(x)&&!enabledRows.includes(x)&&!availableRows.includes(x)),total=all.length,connectedCount=catalog.connectors.filter(connected).length,availableCount=all.filter(x=>availableItem(x.item,x.type)).length;
const records=rows=>rows.map(({item,type})=>row(item,type)).join('')||`<div class="section-empty"><strong>${query?'No apps or tools match this search.':'No items in this section.'}</strong>${query?'<button type="button" class="section-inline-action" data-apps-clear>Clear search</button>':''}</div>`;
body.innerHTML=`<div class="section-page apps-page">${sectionHeader('Apps & Tools','Capabilities and integrations behind Personal AI.')}${sectionSearchMarkup('appsToolsSearch','Search apps, tools or integrations…',query)}${sectionFilterMarkup('appsToolsFilters',[['all','All'],['connected','Connected'],['available','Available'],['tools','Tools'],['integrations','Integrations']],filter)}<div class="activity-stat-grid apps-stat-grid"><button type="button" data-apps-filter="all"><span class="section-action-icon">${sectionIcon('workflow')}</span><strong>${total}</strong><small>Total</small></button><button type="button" data-apps-filter="connected"><span class="section-action-icon completed">${sectionIcon('check')}</span><strong>${connectedCount}</strong><small>Connected</small></button><button type="button" data-apps-filter="available"><span class="section-action-icon">${sectionIcon('plus')}</span><strong>${availableCount}</strong><small>Available</small></button></div><section class="section-list-area"><div class="section-group-heading"><h2>Connected</h2><button type="button" class="section-see-all" data-apps-filter="connected">Manage all ›</button></div>${records(connectedRows)}</section>${enabledRows.length?`<section class="section-list-area"><div class="section-group-heading"><h2>Enabled tools</h2></div>${records(enabledRows)}</section>`:''}<section class="section-list-area"><div class="section-group-heading"><h2>Available tools</h2><button type="button" class="section-see-all" data-apps-filter="available">See all ›</button></div>${records(availableRows)}</section>${attentionRows.length?`<section class="section-list-area"><div class="section-group-heading"><h2>Needs attention</h2></div>${records(attentionRows)}</section>`:''}<div class="apps-security-note">Connections and tool permissions are controlled by this trusted Personal AI device.</div></div>`;
bindSectionHeader();restoreSectionSearchFocus(focus);$('appsToolsSearch').oninput=()=>{query=$('appsToolsSearch').value;render()};document.querySelectorAll('[data-filter-group="appsToolsFilters"],[data-apps-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;render()});document.querySelectorAll('[data-apps-clear]').forEach(button=>button.onclick=()=>{query='';render()});document.querySelectorAll('.apps-detail-toggle').forEach(button=>button.onclick=()=>{const detail=button.closest('.apps-record').querySelector('.apps-record-detail');detail.classList.toggle('hidden');button.setAttribute('aria-expanded',String(!detail.classList.contains('hidden')))});
document.querySelectorAll('[data-connector-connect]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const connector=catalog.connectors.find(item=>item.id===button.dataset.connectorConnect),intent=['authentication_expired','revoked'].includes(connector?.state)?'reconnect':'connect',result=await api('/connectors/'+encodeURIComponent(button.dataset.connectorConnect)+'/oauth/start',{method:'POST',body:JSON.stringify({intent})});if(result.url)location.assign(result.url);else showToast('Connection flow started.')}catch(error){showToast(error.message||'Unable to connect this integration.');button.disabled=false}});
document.querySelectorAll('[data-connector-revoke]').forEach(button=>button.onclick=async()=>{const c=catalog.connectors.find(item=>item.id===button.dataset.connectorRevoke);if(!await requestConfirmation(`Disconnect ${c?.name||'this integration'}? Personal AI will lose its current access.`))return;button.disabled=true;try{await api('/connectors/'+encodeURIComponent(button.dataset.connectorRevoke)+'/revoke',{method:'POST',body:'{}'});await loadTools();showToast('Integration disconnected.')}catch(error){showToast(error.message||'Unable to disconnect this integration.');button.disabled=false}})
}
window.loadTools=async function(){const body=$('moduleBody');document.body.classList.add('focused-module');$('modulePanel').dataset.surface='tools';body.innerHTML=`<div class="section-page apps-page">${sectionHeader('Apps & Tools','Capabilities and integrations behind Personal AI.')}<div class="section-search-skeleton"></div><div class="activity-stat-grid apps-stat-grid"><i></i><i></i><i></i></div><div class="apps-loading-row"></div><div class="apps-loading-row"></div></div>`;try{const [toolData,appData,connectorData]=await Promise.all([api('/apps-tools/tools'),api('/apps-tools/apps'),api('/connectors')]),safeApps=new Map((Array.isArray(appData.apps)?appData.apps:[]).map(app=>[app.app_id,app]));catalog={tools:Array.isArray(toolData.tools)?toolData.tools:[],connectors:(Array.isArray(connectorData.connectors)?connectorData.connectors:[]).map(connector=>{const safe=safeApps.get(connector.id)||{};return {...connector,name:safe.name||connector.name,state:safe.connection_status||connector.state,configured:!!safe.configured,capabilities:safe.capabilities||[],missing_scopes:safe.missing_scopes||[],last_success_at:safe.last_success_at,read_only:!!safe.read_only}})};render()}catch(error){body.innerHTML=`<div class="section-page">${sectionHeader('Apps & Tools','Capabilities and integrations behind Personal AI.')}<section class="section-empty" role="alert"><strong>${error.status===403?'This device is not permitted to manage capabilities.':error.status===401?'Sign in again to manage apps and tools.':'Unable to load apps and tools.'}</strong><button id="appsToolsRetry" class="ui-button" type="button">Retry</button></section></div>`;bindSectionHeader();$('appsToolsRetry').onclick=()=>window.loadTools()}};
})();'''

class ConnectorUiMiddleware(BaseHTTPMiddleware):
    async def dispatch(self,request,call_next):
        response=await call_next(request)
        if request.url.path not in {'/iphone','/iphone/'} or response.status_code!=200:return response
        ctype=response.headers.get('content-type','')
        if 'text/html' not in ctype:return response
        body=b''
        async for chunk in response.body_iterator:body+=chunk
        text=body.decode('utf-8'); marker='</body>'
        if marker in text:text=text.replace(marker,'<script src="/iphone/connector-ui.js"></script>'+marker,1)
        from starlette.responses import Response
        headers={k:v for k,v in response.headers.items() if k.lower() not in {'content-length','content-encoding'}}
        return Response(text,status_code=response.status_code,headers=headers,media_type='text/html')

def connector_ui_router():
    router=APIRouter()
    @router.get('/iphone/connector-ui.js')
    def connector_js():return Response(JS,media_type='application/javascript')
    return router
